// @ts-nocheck
import * as __fd_glob_67 from "../content/docs/database/supabase/tables.mdx?collection=docs"
import * as __fd_glob_66 from "../content/docs/database/supabase/setup.mdx?collection=docs"
import * as __fd_glob_65 from "../content/docs/database/supabase/realtime.mdx?collection=docs"
import * as __fd_glob_64 from "../content/docs/database/supabase/index.mdx?collection=docs"
import * as __fd_glob_63 from "../content/docs/database/postgresql/setup.mdx?collection=docs"
import * as __fd_glob_62 from "../content/docs/database/postgresql/prisma.mdx?collection=docs"
import * as __fd_glob_61 from "../content/docs/database/postgresql/migrations.mdx?collection=docs"
import * as __fd_glob_60 from "../content/docs/database/postgresql/index.mdx?collection=docs"
import * as __fd_glob_59 from "../content/docs/authentication/supabase/social-login.mdx?collection=docs"
import * as __fd_glob_58 from "../content/docs/authentication/supabase/setup.mdx?collection=docs"
import * as __fd_glob_57 from "../content/docs/authentication/supabase/row-level-security.mdx?collection=docs"
import * as __fd_glob_56 from "../content/docs/authentication/supabase/index.mdx?collection=docs"
import * as __fd_glob_55 from "../content/docs/authentication/supabase/email-password.mdx?collection=docs"
import * as __fd_glob_54 from "../content/docs/authentication/better-auth/two-factor.mdx?collection=docs"
import * as __fd_glob_53 from "../content/docs/authentication/better-auth/social-login.mdx?collection=docs"
import * as __fd_glob_52 from "../content/docs/authentication/better-auth/setup.mdx?collection=docs"
import * as __fd_glob_51 from "../content/docs/authentication/better-auth/magic-link.mdx?collection=docs"
import * as __fd_glob_50 from "../content/docs/authentication/better-auth/index.mdx?collection=docs"
import * as __fd_glob_49 from "../content/docs/authentication/better-auth/email-password.mdx?collection=docs"
import * as __fd_glob_48 from "../content/docs/seo/structured-data.mdx?collection=docs"
import * as __fd_glob_47 from "../content/docs/seo/sitemap.mdx?collection=docs"
import * as __fd_glob_46 from "../content/docs/seo/metadata.mdx?collection=docs"
import * as __fd_glob_45 from "../content/docs/seo/index.mdx?collection=docs"
import * as __fd_glob_44 from "../content/docs/payments/webhooks.mdx?collection=docs"
import * as __fd_glob_43 from "../content/docs/payments/subscriptions.mdx?collection=docs"
import * as __fd_glob_42 from "../content/docs/payments/stripe-setup.mdx?collection=docs"
import * as __fd_glob_41 from "../content/docs/payments/index.mdx?collection=docs"
import * as __fd_glob_40 from "../content/docs/payments/customer-portal.mdx?collection=docs"
import * as __fd_glob_39 from "../content/docs/payments/checkout.mdx?collection=docs"
import * as __fd_glob_38 from "../content/docs/getting-started/project-structure.mdx?collection=docs"
import * as __fd_glob_37 from "../content/docs/getting-started/installation.mdx?collection=docs"
import * as __fd_glob_36 from "../content/docs/getting-started/index.mdx?collection=docs"
import * as __fd_glob_35 from "../content/docs/getting-started/environment-variables.mdx?collection=docs"
import * as __fd_glob_34 from "../content/docs/email/transactional.mdx?collection=docs"
import * as __fd_glob_33 from "../content/docs/email/templates.mdx?collection=docs"
import * as __fd_glob_32 from "../content/docs/email/resend-setup.mdx?collection=docs"
import * as __fd_glob_31 from "../content/docs/email/index.mdx?collection=docs"
import * as __fd_glob_30 from "../content/docs/deployment/vercel.mdx?collection=docs"
import * as __fd_glob_29 from "../content/docs/deployment/index.mdx?collection=docs"
import * as __fd_glob_28 from "../content/docs/deployment/environment-variables.mdx?collection=docs"
import * as __fd_glob_27 from "../content/docs/database/index.mdx?collection=docs"
import * as __fd_glob_26 from "../content/docs/components/pricing.mdx?collection=docs"
import * as __fd_glob_25 from "../content/docs/components/modals.mdx?collection=docs"
import * as __fd_glob_24 from "../content/docs/components/index.mdx?collection=docs"
import * as __fd_glob_23 from "../content/docs/components/forms.mdx?collection=docs"
import * as __fd_glob_22 from "../content/docs/components/buttons.mdx?collection=docs"
import * as __fd_glob_21 from "../content/docs/blog/setup.mdx?collection=docs"
import * as __fd_glob_20 from "../content/docs/blog/seo-optimization.mdx?collection=docs"
import * as __fd_glob_19 from "../content/docs/blog/rss.mdx?collection=docs"
import * as __fd_glob_18 from "../content/docs/blog/posts.mdx?collection=docs"
import * as __fd_glob_17 from "../content/docs/blog/index.mdx?collection=docs"
import * as __fd_glob_16 from "../content/docs/blog/categories.mdx?collection=docs"
import * as __fd_glob_15 from "../content/docs/authentication/index.mdx?collection=docs"
import * as __fd_glob_14 from "../content/docs/index.mdx?collection=docs"
import { default as __fd_glob_13 } from "../content/docs/database/supabase/meta.json?collection=docs"
import { default as __fd_glob_12 } from "../content/docs/database/postgresql/meta.json?collection=docs"
import { default as __fd_glob_11 } from "../content/docs/authentication/supabase/meta.json?collection=docs"
import { default as __fd_glob_10 } from "../content/docs/authentication/better-auth/meta.json?collection=docs"
import { default as __fd_glob_9 } from "../content/docs/seo/meta.json?collection=docs"
import { default as __fd_glob_8 } from "../content/docs/payments/meta.json?collection=docs"
import { default as __fd_glob_7 } from "../content/docs/getting-started/meta.json?collection=docs"
import { default as __fd_glob_6 } from "../content/docs/email/meta.json?collection=docs"
import { default as __fd_glob_5 } from "../content/docs/deployment/meta.json?collection=docs"
import { default as __fd_glob_4 } from "../content/docs/database/meta.json?collection=docs"
import { default as __fd_glob_3 } from "../content/docs/components/meta.json?collection=docs"
import { default as __fd_glob_2 } from "../content/docs/blog/meta.json?collection=docs"
import { default as __fd_glob_1 } from "../content/docs/authentication/meta.json?collection=docs"
import { default as __fd_glob_0 } from "../content/docs/meta.json?collection=docs"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>({"doc":{"passthroughs":["extractedReferences"]}});

export const docs = await create.docs("docs", "content/docs", {"meta.json": __fd_glob_0, "authentication/meta.json": __fd_glob_1, "blog/meta.json": __fd_glob_2, "components/meta.json": __fd_glob_3, "database/meta.json": __fd_glob_4, "deployment/meta.json": __fd_glob_5, "email/meta.json": __fd_glob_6, "getting-started/meta.json": __fd_glob_7, "payments/meta.json": __fd_glob_8, "seo/meta.json": __fd_glob_9, "authentication/better-auth/meta.json": __fd_glob_10, "authentication/supabase/meta.json": __fd_glob_11, "database/postgresql/meta.json": __fd_glob_12, "database/supabase/meta.json": __fd_glob_13, }, {"index.mdx": __fd_glob_14, "authentication/index.mdx": __fd_glob_15, "blog/categories.mdx": __fd_glob_16, "blog/index.mdx": __fd_glob_17, "blog/posts.mdx": __fd_glob_18, "blog/rss.mdx": __fd_glob_19, "blog/seo-optimization.mdx": __fd_glob_20, "blog/setup.mdx": __fd_glob_21, "components/buttons.mdx": __fd_glob_22, "components/forms.mdx": __fd_glob_23, "components/index.mdx": __fd_glob_24, "components/modals.mdx": __fd_glob_25, "components/pricing.mdx": __fd_glob_26, "database/index.mdx": __fd_glob_27, "deployment/environment-variables.mdx": __fd_glob_28, "deployment/index.mdx": __fd_glob_29, "deployment/vercel.mdx": __fd_glob_30, "email/index.mdx": __fd_glob_31, "email/resend-setup.mdx": __fd_glob_32, "email/templates.mdx": __fd_glob_33, "email/transactional.mdx": __fd_glob_34, "getting-started/environment-variables.mdx": __fd_glob_35, "getting-started/index.mdx": __fd_glob_36, "getting-started/installation.mdx": __fd_glob_37, "getting-started/project-structure.mdx": __fd_glob_38, "payments/checkout.mdx": __fd_glob_39, "payments/customer-portal.mdx": __fd_glob_40, "payments/index.mdx": __fd_glob_41, "payments/stripe-setup.mdx": __fd_glob_42, "payments/subscriptions.mdx": __fd_glob_43, "payments/webhooks.mdx": __fd_glob_44, "seo/index.mdx": __fd_glob_45, "seo/metadata.mdx": __fd_glob_46, "seo/sitemap.mdx": __fd_glob_47, "seo/structured-data.mdx": __fd_glob_48, "authentication/better-auth/email-password.mdx": __fd_glob_49, "authentication/better-auth/index.mdx": __fd_glob_50, "authentication/better-auth/magic-link.mdx": __fd_glob_51, "authentication/better-auth/setup.mdx": __fd_glob_52, "authentication/better-auth/social-login.mdx": __fd_glob_53, "authentication/better-auth/two-factor.mdx": __fd_glob_54, "authentication/supabase/email-password.mdx": __fd_glob_55, "authentication/supabase/index.mdx": __fd_glob_56, "authentication/supabase/row-level-security.mdx": __fd_glob_57, "authentication/supabase/setup.mdx": __fd_glob_58, "authentication/supabase/social-login.mdx": __fd_glob_59, "database/postgresql/index.mdx": __fd_glob_60, "database/postgresql/migrations.mdx": __fd_glob_61, "database/postgresql/prisma.mdx": __fd_glob_62, "database/postgresql/setup.mdx": __fd_glob_63, "database/supabase/index.mdx": __fd_glob_64, "database/supabase/realtime.mdx": __fd_glob_65, "database/supabase/setup.mdx": __fd_glob_66, "database/supabase/tables.mdx": __fd_glob_67, });